package com.zapp.oneweatherzapp;

import com.google.firebase.remoteconfig.FirebaseRemoteConfig;
/* compiled from: TypeScaleTokens.kt */
/* loaded from: classes.dex */
public final class g35 {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final y81 D;
    public static final mg1 E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final y81 I;
    public static final mg1 J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final y81 N;
    public static final mg1 O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final y81 S;
    public static final mg1 T;
    public static final long U;
    public static final long V;
    public static final long W;
    public static final y81 X;
    public static final mg1 Y;
    public static final long Z;
    public static final mg1 a;
    public static final long a0;
    public static final long b;
    public static final long b0;
    public static final long c;
    public static final y81 c0;
    public static final long d;
    public static final mg1 d0;
    public static final y81 e;
    public static final long e0;
    public static final mg1 f;
    public static final long f0;
    public static final long g;
    public static final long g0;
    public static final long h;
    public static final y81 h0;
    public static final long i;
    public static final mg1 i0;
    public static final y81 j;
    public static final long j0;
    public static final mg1 k;
    public static final long k0;
    public static final long l;
    public static final long l0;
    public static final long m;
    public static final y81 m0;
    public static final long n;
    public static final mg1 n0;
    public static final y81 o;
    public static final long o0;
    public static final mg1 p;
    public static final long p0;
    public static final long q;
    public static final long q0;
    public static final long r;
    public static final y81 r0;
    public static final long s;
    public static final mg1 s0;
    public static final y81 t;
    public static final long t0;
    public static final mg1 u;
    public static final long u0;
    public static final long v;
    public static final long v0;
    public static final long w;
    public static final y81 w0;
    public static final long x;
    public static final y81 y;
    public static final mg1 z;

    static {
        mg1 mg1Var = i45.b;
        a = mg1Var;
        b = iv1.a(24.0d);
        c = iv1.c(16);
        d = iv1.a(0.5d);
        y81 y81Var = i45.d;
        e = y81Var;
        f = mg1Var;
        g = iv1.a(20.0d);
        h = iv1.c(14);
        i = iv1.a(0.2d);
        j = y81Var;
        k = mg1Var;
        l = iv1.a(16.0d);
        m = iv1.c(12);
        n = iv1.a(0.4d);
        o = y81Var;
        mg1 mg1Var2 = i45.a;
        p = mg1Var2;
        q = iv1.a(64.0d);
        r = iv1.c(57);
        long a2 = iv1.a(0.2d);
        if (!iv1.f(a2)) {
            s = iv1.g(-vt4.c(a2), a2 & 1095216660480L);
            t = y81Var;
            u = mg1Var2;
            v = iv1.a(52.0d);
            w = iv1.c(45);
            x = iv1.a(FirebaseRemoteConfig.DEFAULT_VALUE_FOR_DOUBLE);
            y = y81Var;
            z = mg1Var2;
            A = iv1.a(44.0d);
            B = iv1.c(36);
            C = iv1.a(FirebaseRemoteConfig.DEFAULT_VALUE_FOR_DOUBLE);
            D = y81Var;
            E = mg1Var2;
            F = iv1.a(40.0d);
            G = iv1.c(32);
            H = iv1.a(FirebaseRemoteConfig.DEFAULT_VALUE_FOR_DOUBLE);
            I = y81Var;
            J = mg1Var2;
            K = iv1.a(36.0d);
            L = iv1.c(28);
            M = iv1.a(FirebaseRemoteConfig.DEFAULT_VALUE_FOR_DOUBLE);
            N = y81Var;
            O = mg1Var2;
            P = iv1.a(32.0d);
            Q = iv1.c(24);
            R = iv1.a(FirebaseRemoteConfig.DEFAULT_VALUE_FOR_DOUBLE);
            S = y81Var;
            T = mg1Var;
            U = iv1.a(20.0d);
            V = iv1.c(14);
            W = iv1.a(0.1d);
            y81 y81Var2 = i45.c;
            X = y81Var2;
            Y = mg1Var;
            Z = iv1.a(16.0d);
            a0 = iv1.c(12);
            b0 = iv1.a(0.5d);
            c0 = y81Var2;
            d0 = mg1Var;
            e0 = iv1.a(16.0d);
            f0 = iv1.c(11);
            g0 = iv1.a(0.5d);
            h0 = y81Var2;
            i0 = mg1Var2;
            j0 = iv1.a(28.0d);
            k0 = iv1.c(22);
            l0 = iv1.a(FirebaseRemoteConfig.DEFAULT_VALUE_FOR_DOUBLE);
            m0 = y81Var;
            n0 = mg1Var;
            o0 = iv1.a(24.0d);
            p0 = iv1.c(16);
            q0 = iv1.a(0.2d);
            r0 = y81Var2;
            s0 = mg1Var;
            t0 = iv1.a(20.0d);
            u0 = iv1.c(14);
            v0 = iv1.a(0.1d);
            w0 = y81Var2;
            return;
        }
        throw new IllegalArgumentException("Cannot perform operation for Unspecified type.".toString());
    }
}
