package com.zapp.oneweatherzapp;

import com.glance.spaces.common.ZappWidgetId;
import com.zapp.oneweatherzapp.presentation.constants.AppConstants;
/* compiled from: Key.android.kt */
@t22
/* loaded from: classes.dex */
public final class n42 {
    public static final long b;
    public static final long c;
    public static final long d;
    public static final long e;
    public static final long f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final long j;
    public static final long k;
    public static final long l;
    public static final long m;
    public static final /* synthetic */ int n = 0;
    public final long a;

    static {
        ha.e(0);
        ha.e(1);
        ha.e(2);
        ha.e(3);
        b = ha.e(4);
        ha.e(259);
        ha.e(260);
        ha.e(261);
        ha.e(262);
        ha.e(263);
        ha.e(280);
        ha.e(281);
        ha.e(282);
        ha.e(283);
        ha.e(5);
        ha.e(6);
        c = ha.e(19);
        d = ha.e(20);
        e = ha.e(21);
        f = ha.e(22);
        g = ha.e(23);
        ha.e(268);
        ha.e(269);
        ha.e(270);
        ha.e(271);
        ha.e(24);
        ha.e(25);
        ha.e(26);
        ha.e(27);
        ha.e(28);
        ha.e(7);
        ha.e(8);
        ha.e(9);
        ha.e(10);
        ha.e(11);
        ha.e(12);
        ha.e(13);
        ha.e(14);
        ha.e(15);
        ha.e(16);
        ha.e(81);
        ha.e(69);
        ha.e(17);
        ha.e(70);
        ha.e(18);
        ha.e(29);
        ha.e(30);
        ha.e(31);
        ha.e(32);
        ha.e(33);
        ha.e(34);
        ha.e(35);
        ha.e(36);
        ha.e(37);
        ha.e(38);
        ha.e(39);
        ha.e(40);
        ha.e(41);
        ha.e(42);
        ha.e(43);
        ha.e(44);
        ha.e(45);
        ha.e(46);
        ha.e(47);
        ha.e(48);
        ha.e(49);
        ha.e(50);
        ha.e(51);
        ha.e(52);
        ha.e(53);
        ha.e(54);
        ha.e(55);
        ha.e(56);
        ha.e(57);
        ha.e(58);
        ha.e(59);
        ha.e(60);
        h = ha.e(61);
        ha.e(62);
        ha.e(63);
        ha.e(64);
        ha.e(65);
        i = ha.e(66);
        ha.e(67);
        ha.e(ZappWidgetId.L0_ID_GAMES_FEATURED_GAMES_MD_V1_VALUE);
        j = ha.e(ZappWidgetId.L0_ID_GAMES_CONTINUE_PLAYING_GAMES_MD_V1_VALUE);
        ha.e(ZappWidgetId.L0_ID_GAMES_LIVE_GAMES_MD_V1_VALUE);
        ha.e(ZappWidgetId.L0_ID_GAMES_NEW_ARRIVALS_GAMES_MD_V1_VALUE);
        ha.e(ZappWidgetId.L0_ID_GAMES_EDITORS_CHOICE_GAMES_MD_V1_VALUE);
        ha.e(ZappWidgetId.L0_ID_GAMES_COMMUNITY_GAMES_MD_V1_VALUE);
        ha.e(ZappWidgetId.L0_ID_GAMES_TOP_INSTANT_GAMES_MD_V1_VALUE);
        ha.e(ZappWidgetId.SHOP_DAILY_DEAL_XL_V1_VALUE);
        ha.e(ZappWidgetId.SHOP_HEADLINES_XXL_V2_VALUE);
        ha.e(ZappWidgetId.GAMES_INSTANT_GAME_XXL_V1_VALUE);
        ha.e(ZappWidgetId.ENTERTAINMENT_BUZZ_HOT_TOPIC_XL_V1_VALUE);
        ha.e(ZappWidgetId.ENTERTAINMENT_BUZZ_TRENDS_XXL_V1_VALUE);
        ha.e(ZappWidgetId.L0_ID_ENTERTAINMENT_BUZZ_ENTERTAINMENT_LN_V1_VALUE);
        ha.e(ZappWidgetId.L0_ID_ENTERTAINMENT_BUZZ_ENTERTAINMENT_MD_V1_VALUE);
        ha.e(277);
        ha.e(278);
        ha.e(279);
        ha.e(68);
        ha.e(71);
        ha.e(72);
        ha.e(76);
        ha.e(73);
        ha.e(74);
        ha.e(75);
        ha.e(77);
        ha.e(78);
        ha.e(79);
        ha.e(80);
        ha.e(82);
        ha.e(83);
        ha.e(84);
        k = ha.e(92);
        l = ha.e(93);
        ha.e(94);
        ha.e(95);
        ha.e(96);
        ha.e(97);
        ha.e(98);
        ha.e(99);
        ha.e(100);
        ha.e(ZappWidgetId.L0_ID_SPORTS_NHL_MATCH_LN_V1_VALUE);
        ha.e(ZappWidgetId.L0_ID_TRENDZ_NEWS_HEADLINES_LN_V2_VALUE);
        ha.e(ZappWidgetId.L0_ID_SPORTS_NBA_HEADLINES_LN_V2_VALUE);
        ha.e(ZappWidgetId.L0_ID_SPORTS_NFL_HEADLINES_LN_V2_VALUE);
        ha.e(ZappWidgetId.L0_ID_SPORTS_NHL_HEADLINES_LN_V2_VALUE);
        ha.e(ZappWidgetId.L0_ID_SPORTS_MLB_HEADLINES_LN_V2_VALUE);
        ha.e(ZappWidgetId.L0_ID_TRENDZ_BREAKING_NEWS_MD_V1_VALUE);
        ha.e(ZappWidgetId.L0_ID_TRENDZ_BREAKING_NEWS_LN_V2_VALUE);
        ha.e(ZappWidgetId.L0_ID_TRENDZ_NEWS_ONE_WEATHER_LN_V1_VALUE);
        ha.e(ZappWidgetId.L0_ID_GAMES_TOP_THREE_GAMES_MD_V1_VALUE);
        ha.e(188);
        ha.e(189);
        ha.e(190);
        ha.e(191);
        ha.e(192);
        ha.e(193);
        ha.e(194);
        ha.e(195);
        ha.e(196);
        ha.e(197);
        ha.e(198);
        ha.e(199);
        ha.e(200);
        ha.e(201);
        ha.e(202);
        ha.e(203);
        ha.e(ZappWidgetId.ENTERTAINMENT_ARTICLES_HEADLINES_XXL_V2_VALUE);
        ha.e(ZappWidgetId.L0_ID_SHOP_DAILY_DEAL_LN_V1_VALUE);
        ha.e(ZappWidgetId.L0_ID_SHOP_SMART_GADGETS_LN_V1_VALUE);
        ha.e(ZappWidgetId.L0_ID_SHOP_TRENDING_TODAY_LN_V1_VALUE);
        ha.e(ZappWidgetId.L0_ID_SHOP_BUDGET_BUY_LN_V1_VALUE);
        ha.e(ZappWidgetId.L0_ID_SHOP_DAILY_DEAL_MD_V1_VALUE);
        ha.e(ZappWidgetId.L0_ID_SHOP_SMART_GADGETS_MD_V1_VALUE);
        ha.e(ZappWidgetId.L0_ID_SHOP_TRENDING_TODAY_MD_V1_VALUE);
        ha.e(ZappWidgetId.L0_ID_SHOP_BUDGET_BUY_MD_V1_VALUE);
        ha.e(ZappWidgetId.SPORTS_BDS_LEAGUE_MATCH_XXL_V1_VALUE);
        ha.e(ZappWidgetId.SPORTS_BDS_TEAM_MATCH_XXL_V1_VALUE);
        ha.e(ZappWidgetId.SPORTS_BDS_HEADLINES_XXL_V1_VALUE);
        ha.e(ZappWidgetId.SPORTS_BDS_OFF_SEASON_MXL_V1_VALUE);
        ha.e(ZappWidgetId.SPORTS_BDS_ROUNDUP_MXL_V1_VALUE);
        ha.e(ZappWidgetId.SPORTS_BDS_STANDINGS_XXL_V1_VALUE);
        ha.e(ZappWidgetId.L0_ID_SPORTS_BDS_MATCH_XS_V1_VALUE);
        ha.e(ZappWidgetId.L0_ID_SPORTS_BDS_MATCH_LN_V1_VALUE);
        ha.e(ZappWidgetId.L0_ID_SPORTS_BDS_HEADLINES_MD_V1_VALUE);
        ha.e(ZappWidgetId.L0_ID_SPORTS_BDS_HEADLINES_LN_V1_VALUE);
        ha.e(ZappWidgetId.L0_ID_SPORTS_BDS_ROUNDUP_LN_V1_VALUE);
        ha.e(ZappWidgetId.L0_ID_SPORTS_BDS_ROUNDUP_MXL_V1_VALUE);
        ha.e(ZappWidgetId.TRENDZ_INFINITY_SCROLL_LV_V1_VALUE);
        ha.e(ZappWidgetId.SPORTS_MLB_INFINITY_SCROLL_LV_V1_VALUE);
        ha.e(ZappWidgetId.SPORTS_NBA_INFINITY_SCROLL_LV_V1_VALUE);
        ha.e(ZappWidgetId.SPORTS_NFL_INFINITY_SCROLL_LV_V1_VALUE);
        ha.e(ZappWidgetId.SPORTS_NHL_INFINITY_SCROLL_LV_V1_VALUE);
        ha.e(ZappWidgetId.GLANCE_GLOBAL_LOCATION_PREFERENCE_LH_V1_VALUE);
        ha.e(ZappWidgetId.HOME_HOROSCOPE_LH_V1_VALUE);
        ha.e(158);
        ha.e(159);
        m = ha.e(160);
        ha.e(161);
        ha.e(162);
        ha.e(163);
        ha.e(126);
        ha.e(127);
        ha.e(85);
        ha.e(86);
        ha.e(ZappWidgetId.L0_ID_GAMES_INSTANT_GAME_GAMES_MD_V1_VALUE);
        ha.e(87);
        ha.e(88);
        ha.e(89);
        ha.e(90);
        ha.e(128);
        ha.e(222);
        ha.e(ZappWidgetId.L0_ID_GAMES_INSTANT_GAME_GAMES_LN_V1_VALUE);
        ha.e(226);
        ha.e(272);
        ha.e(273);
        ha.e(274);
        ha.e(275);
        ha.e(91);
        ha.e(164);
        ha.e(165);
        ha.e(166);
        ha.e(167);
        ha.e(168);
        ha.e(169);
        ha.e(170);
        ha.e(171);
        ha.e(172);
        ha.e(173);
        ha.e(174);
        ha.e(175);
        ha.e(176);
        ha.e(177);
        ha.e(178);
        ha.e(179);
        ha.e(AppConstants.RAISING);
        ha.e(181);
        ha.e(182);
        ha.e(183);
        ha.e(184);
        ha.e(185);
        ha.e(186);
        ha.e(187);
        ha.e(204);
        ha.e(205);
        ha.e(206);
        ha.e(207);
        ha.e(208);
        ha.e(209);
        ha.e(210);
        ha.e(211);
        ha.e(212);
        ha.e(213);
        ha.e(214);
        ha.e(215);
        ha.e(216);
        ha.e(217);
        ha.e(218);
        ha.e(219);
        ha.e(220);
        ha.e(221);
        ha.e(223);
        ha.e(224);
        ha.e(276);
        ha.e(225);
        ha.e(229);
        ha.e(230);
        ha.e(231);
        ha.e(232);
        ha.e(233);
        ha.e(234);
        ha.e(235);
        ha.e(236);
        ha.e(237);
        ha.e(238);
        ha.e(239);
        ha.e(240);
        ha.e(241);
        ha.e(242);
        ha.e(243);
        ha.e(244);
        ha.e(245);
        ha.e(246);
        ha.e(247);
        ha.e(248);
        ha.e(249);
        ha.e(250);
        ha.e(251);
        ha.e(252);
        ha.e(253);
        ha.e(254);
        ha.e(255);
        ha.e(256);
        ha.e(257);
        ha.e(258);
        ha.e(264);
        ha.e(265);
        ha.e(266);
        ha.e(267);
        ha.e(284);
        ha.e(285);
        ha.e(286);
        ha.e(287);
        ha.e(288);
    }

    public static final boolean a(long j2, long j3) {
        if (j2 == j3) {
            return true;
        }
        return false;
    }

    public final boolean equals(Object obj) {
        if (!(obj instanceof n42)) {
            return false;
        }
        if (this.a != ((n42) obj).a) {
            return false;
        }
        return true;
    }

    public final int hashCode() {
        return Long.hashCode(this.a);
    }

    public final String toString() {
        return "Key code: " + this.a;
    }
}
