package com.zapp.oneweatherzapp;
/* compiled from: ColorLightTokens.kt */
/* loaded from: classes.dex */
public final class vz {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final long D;
    public static final long E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final long I;
    public static final long a;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final long e;
    public static final long f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final long j;
    public static final long k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final long o;
    public static final long p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final long t;
    public static final long u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final long y;
    public static final long z;

    static {
        long j2 = ia3.x;
        a = j2;
        b = ia3.e;
        c = ia3.g;
        d = ia3.u;
        e = ia3.I;
        f = ia3.m;
        long j3 = ia3.i;
        g = j3;
        h = ia3.b;
        i = ia3.a;
        j = ia3.E;
        k = ia3.D;
        l = ia3.L;
        m = ia3.K;
        n = j3;
        o = ia3.y;
        p = ia3.S;
        q = ia3.R;
        r = ia3.z;
        s = ia3.B;
        t = ia3.H;
        u = ia3.J;
        v = ia3.h;
        w = ia3.O;
        x = ia3.Q;
        y = j2;
        z = ia3.w;
        A = ia3.t;
        B = ia3.s;
        C = ia3.r;
        D = ia3.v;
        E = ia3.j;
        F = ia3.q;
        G = ia3.C;
        H = ia3.V;
        I = ia3.X;
    }
}
